version: "3.8"

services:
  frontend:
    image: aiyus/dream-frontend:${FRONTEND_TAG}
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - vacation-net

  backend:
    image: aiyus/dream-backend:${BACKEND_TAG}
    expose:
      - "5000"
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - vacation-net

  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    networks:
      - vacation-net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - vacation-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    entrypoint: >
      sh -c "certbot certonly --webroot 
      --webroot-path=/var/www/html 
      -d aiyusdreamapp.name.ng 
      -d www.aiyusdreamapp.name.ng 
      --email aiyusboss@gmail.com --agree-tos --non-interactive || true"

volumes:
  pgdata:
  letsencrypt:

networks:
  vacation-net:
    driver: bridge
