version: "3.8"

services:
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-www:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  frontend:
    image: aiyus/dream-frontend:${FRONTEND_TAG}
    restart: always

  backend:
    image: aiyus/dream-backend:${BACKEND_TAG}
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do
        sleep 12h & wait $${!};
        certbot renew --webroot -w /var/www/certbot --quiet;
        nginx_pid=$(docker inspect --format '{{ .State.Pid }}' nginx_proxy);
        if [ -n \"$nginx_pid\" ]; then
          docker exec nginx_proxy nginx -s reload;
        fi
      done"

volumes:
  db-data:
  certbot-www:
  certbot-certs:
