server {
    listen 80;
    server_name ;
    root /var/www/example.com;
    index index.html;
}

server {
    listen 443 ssl;
    server_name aiyusdreamapp.name.ng;

    ssl_certificate /etc/letsencrypt/live/aiyusdreamapp.name.ng/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aiyusdreamapp.name.ng/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # React frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}
