server {
    listen 80;
    server_name aiyusdreamapp.name.ng www.aiyusdreamapp.name.ng;

    location / {
        proxy_pass http://localhost:3000;   # frontend container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
        proxy_pass http://localhost:5000;   # backend container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    server_name aiyusdreamapp.name.ng;

    ssl_certificate /etc/letsencrypt/live/aiyusdreamapp.name.ng/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aiyusdreamapp.name.ng/privkey.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
