name: Deploy Dream Vacation App

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sync files to EC2
      - name: Sync files to EC2 with rsync
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avz --delete 
          path: ./
          remote_path: /home/ubuntu/dream-vacation
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_SSH_KEY }}
      # Deploy app on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/dream-vacation
            docker-compose pull
            docker-compose up -d --build
